[env]
PORT = "8080"

[config]
skip_core_tasks = true

# ---- GENERAL ----

[tasks.verify]
description = "Format, lint with Clippy and run tests"
dependencies = ["fmt", "clippy", "fmt_prettier"]

[tasks.verify_only]
description = "Like `verify`, but fails if the code isn't formatted. Primarily for CI."
dependencies = ["fmt_check", "clippy", "fmt_prettier_check", "test_h_firefox"]

# ---- BASIC ----

[tasks.clean]
description = "Remove build output"
script = [
    "rm -rf dist",
    "rm -f src/generated/css_classes.rs"
]

[tasks.serve]
description = "Start server"
install_crate = { crate_name = "trunk", binary = "trunk", test_arg = "-V" }
command = "trunk"
args = ["serve"]
dependencies = ["prepare"]

[tasks.serve_release]
description = "Start real web server"
install_crate = { crate_name = "microserver", binary = "microserver", test_arg = "-h" }
command = "microserver"
args = ["dist/", "--port", "${PORT}"]
dependencies = ["build_release"]

# ---- BUILD ----

[tasks.build_release]
description = "Build with trunk"
install_crate = { crate_name = "trunk", binary = "trunk", test_arg = "-V" }
command = "trunk"
args = ["build", "--release"]
dependencies = ["prepare_release"]

[tasks.prepare]
description = "Prepare asset"
install_crate = { crate_name = "trunk", binary = "trunk", test_arg = "-V" }
command = "npx"
args = ["postcss", "--config", "configs/postcss.config.js", "sass/main.scss", "--output", "sass/compiled.scss"]

[tasks.prepare_release]
description = "Prepare asset for release"
command = "npx"
args = ["postcss", "--config", "configs/postcss.config.js", "sass/main.scss", "--output", "sass/compiled.scss", "--env", "production"]

# ---- LINT ----

[tasks.clippy]
description = "Lint with Clippy"
install_crate = { rustup_component_name = "clippy", binary = "cargo-clippy", test_arg = "--help" }
command = "cargo"
args = ["clippy", "--all-features", "--", "--deny", "warnings", "--deny", "clippy::pedantic", "--deny", "clippy::nursery"]

[tasks.fmt]
description = "Format with nightly rustfmt"
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--all"]

[tasks.fmt_check]
extend = "fmt"
description = "Check format with nightly rustfmt"
args = ["fmt", "--all", "--", "--check"]

[tasks.fmt_prettier]
description = "Format with prettier"
command = "prettier"
args = ["--config", "configs/prettier.config.js", "--ignore-path", "configs/prettierignore", "--write", "."]

[tasks.fmt_prettier_check]
description = "Check format with prettier"
command = "prettier"
args = ["--config", "configs/prettier.config.js", "--ignore-path", "configs/prettierignore", "--check", "."]

# ---- TEST ----

[tasks.test_h_firefox]
description = "Run headless tests with Firefox."
extend = "test"
args = ["test", "--headless", "--firefox"]

[tasks.test_h]
description = "Run headless tests. Ex: 'cargo make test_h firefox'. Test envs: [chrome, firefox, safari]"
extend = "test"
args = ["test", "--headless", "--${@}"]

[tasks.test]
description = "Run tests. Ex: 'cargo make test firefox'. Test envs: [chrome, firefox, safari]"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["test", "--${@}"]
dependencies = ["prepare"]
